// <auto-generated />
using Media.Player.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Media.Player.Migrations
{
    [DbContext(typeof(MediaPlayerContext))]
    [Migration("20180423144216_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Media.Player.Domain.MediaMetadata", b =>
                {
                    b.Property<int>("MediaMetadataId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("MediaMetadataId");

                    b.ToTable("MediaMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
